controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


search:
    path: /search
    controller: App\Controller\SearchController::searchAction
    methods: [GET]


app_compte_supprimer:
    path: /compte/supprimer
    controller: App\Controller\CompteController::supprimerCompte


admin:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index

update_etat_commande:
    path: /admin/commande/{id}/etat
    controller: App\Controller\Admin\DashboardController::updateEtat
    methods: [POST]
    requirements:
        id: \d+