controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


search:
    path: /search
    controller: App\Controller\SearchController::searchAction
    methods: [GET]


app_compte_supprimer:
    path: /compte/supprimer
    controller: App\Controller\CompteController::supprimerCompte